table 'Comparable Flag'
	lineageTag: 33ca01f1-e252-4547-a98d-2b4f0664e773

	column ID_Comparable_flag
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d67db45e-4471-4a49-917b-65d2251e4542
		summarizeBy: none
		sourceColumn: ID_Comparable_flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Comparable flag'
		dataType: string
		lineageTag: 4bd71c21-d8df-427d-ac33-b3c9e4ec5ec9
		summarizeBy: none
		sourceColumn: Comparable flag

		annotation SummarizationSetBy = Automatic

	column 'Comparable flag Y-1'
		dataType: string
		lineageTag: 43a2f09b-82f4-4759-be90-635b8c76aa50
		summarizeBy: none
		sourceColumn: Comparable flag Y-1

		annotation SummarizationSetBy = Automatic

	partition 'Comparable Flag' = m
		mode: import
		queryGroup: '01.Dimensions'
		source = ```
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject=P_Billing_Project]){[Name=P_Project_Name]}[Data], "
				    SELECT
				    ID_Comparable_flag,
				    Comparable_flag,
				    Comparable_flag_Y_1
				FROM 
				    `expo_self_bi_sales.comparable_flag`
				    ", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Comparable_flag", "Comparable flag"}, {"Comparable_flag_Y_1", "Comparable flag Y-1"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

