table Store
	lineageTag: 5ab2895e-1ae2-4a91-be78-b8c107551af0

	column Region
		dataType: string
		lineageTag: c8a575ac-a62f-4c98-ade6-68f598c3f32a
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Direction
		dataType: string
		lineageTag: e7f2c2e6-38b1-4652-b7ff-fe704ce730a6
		summarizeBy: none
		sourceColumn: Direction

		annotation SummarizationSetBy = Automatic

	column Cluster
		dataType: string
		lineageTag: 9297022c-9793-4133-b092-75d23697d238
		summarizeBy: none
		sourceColumn: Cluster

		annotation SummarizationSetBy = Automatic

	column ID_Store
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 10637183-866c-45d2-a5a4-ca465deccd5f
		summarizeBy: none
		sourceColumn: ID_Store

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Store name'
		dataType: string
		lineageTag: 757777a4-0c6b-4b5b-9890-28975bb6164f
		summarizeBy: none
		sourceColumn: Store name

		annotation SummarizationSetBy = Automatic

	column 'Store code 3'
		dataType: string
		lineageTag: 93f2b915-153d-436f-b0d9-30a347933e62
		summarizeBy: none
		sourceColumn: Store code 3

		annotation SummarizationSetBy = Automatic

	column 'Store code 5'
		dataType: string
		lineageTag: fab4c4ce-0b0e-43f3-ae9f-71df7c43cc20
		summarizeBy: none
		sourceColumn: Store code 5

		annotation SummarizationSetBy = Automatic

	column Typology
		dataType: string
		lineageTag: b87f7f5b-99f2-4f65-bb33-7cd496150486
		summarizeBy: none
		sourceColumn: Typology

		annotation SummarizationSetBy = Automatic

	column 'Public accessible surface'
		dataType: double
		lineageTag: 612eb397-790e-40b1-a449-f8c603cf6f1e
		summarizeBy: none
		sourceColumn: Public accessible surface

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Storage surface'
		dataType: double
		lineageTag: 77f508bc-3ade-447e-acfb-ccbb5feb171e
		summarizeBy: none
		sourceColumn: Storage surface

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net internal surface'
		dataType: double
		lineageTag: 827e8719-97bc-4780-be8d-c66ca0577004
		summarizeBy: none
		sourceColumn: Net internal surface

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Distribution zone'
		dataType: string
		lineageTag: 4096497e-a998-46d2-80aa-56d95b454e8f
		summarizeBy: none
		sourceColumn: Distribution zone

		annotation SummarizationSetBy = Automatic

	column 'Opening date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 18c537b8-f929-42a5-a690-b0e7d1074b4c
		summarizeBy: none
		sourceColumn: Opening date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Closing date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 06b74400-d183-4918-8f82-ef10cab038c9
		summarizeBy: none
		sourceColumn: Closing date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Legal structure'
		dataType: string
		lineageTag: 65892821-3353-428c-81d7-455074a0c943
		summarizeBy: none
		sourceColumn: Legal structure

		annotation SummarizationSetBy = Automatic

	column 'Country code'
		dataType: string
		lineageTag: 4de47fba-df7c-4588-8d7d-99cad5030c62
		summarizeBy: none
		sourceColumn: Country code

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: 2490df58-742c-4219-9b70-b83f68f09f4d
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column 'Store status'
		dataType: string
		lineageTag: 693d2912-a884-4bd1-b9f7-81a97f842a9a
		summarizeBy: none
		sourceColumn: Store status

		annotation SummarizationSetBy = Automatic

	column 'Double store code'
		dataType: string
		lineageTag: 36563ea9-4d03-4c31-93d8-8d62c12f8724
		summarizeBy: none
		sourceColumn: Double store code

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 28d8ff3e-dbb9-4ba3-8f55-658e284bf5ea
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: b3ecb31d-dad0-40d2-baca-bc265a56d94c
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Commercial model'
		dataType: string
		lineageTag: 2126a222-15c4-4023-8093-6da6f3f184c7
		summarizeBy: none
		sourceColumn: Commercial model

		annotation SummarizationSetBy = Automatic

	column 'Business unit'
		dataType: string
		lineageTag: 04e05d2d-bc10-44b6-87a0-0154e949de61
		summarizeBy: none
		sourceColumn: Business unit

		annotation SummarizationSetBy = Automatic

	partition Store = m
		mode: import
		queryGroup: '01.Dimensions'
		source = ```
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject=P_Billing_Project]){[Name=P_Project_Name]}[Data], "
				    		 /* SELECT
								    ID_Store,
								    Store_name,
								    Store_3_code,
								    Store_5_code,
								    Region,
								    Direction,
								    Cluster,
								    Typology,
								    Public_accessible_surface,
								    Storage_surface,
								    Net_internal_surface,
								    Distribution_zone,
								    Opening_date,
								    Closing_date,
								    Legal_structure,
								    Country_code,
								    Currency,
								    Store_status,
								    Double_coque_code,
								    Latitude,
								    Longitude
								FROM 
								    `expo_self_bi_sales.store`
								ORDER BY 
								    ID_Store */
								
								SELECT
								    a.ID_Store,
								    Store_name,
								    Store_3_code,
								    Store_5_code,
								    Region,
								    Direction,
								    Cluster,
								    Typology,
								    Public_accessible_surface,
								    Storage_surface,
								    Net_internal_surface,
								    Distribution_zone,
								    Opening_date,
								    Closing_date,
								    Legal_structure,
								    Country_code,
								    Currency,
								    Store_status,
								    Double_coque_code,
								    Latitude,
								    Longitude,
								    Business_unit,
								          CASE 
								    WHEN lb_contract_type = 'K' AND Store_5_code IN (SELECT  id_store
								  FROM `solution.stores`
								  WHERE lb_assortment_zone_type = 'web'
								    AND lb_distribution_type = 'WEB'
								    AND lb_contract_type = 'K'
								    AND flag_is_opened
								    AND id_store NOT IN ('WEBWW', 'WEBSH', 'B2B2G')) THEN 'Web'
								    WHEN lb_contract_type = 'K' THEN 'Succursales'
								    WHEN lb_contract_type = 'A' THEN 'Affiliés'
								    WHEN lb_contract_type = 'F' THEN 'Franchisés'
								  END AS commercial_model
								FROM 
								    `expo_self_bi_sales.store` a 
								    left join (select 
								id_store as store_5, case when lb_world_group ='EUR LATAM' then 'EULAT'
								when lb_world_group ='AMEA' then lb_world_group
								when lb_world_group ='KIFS' then 'EULAT'
								else lb_direction
								end as lb_key_countries_groups,
								from solution.stores_legacy a
								left join solution.regions b on a._id_region=b._id_region
								left join solution.sales_directions c on b._id_sales_direction=c._id_sales_direction
								left join solution.directions d on c._id_direction=d._id_direction
								left join `solution.world_group`e on d._id_world_group=e._id_world_group
								) b on a.store_5_code=b.store_5
								left join solution.stores c on a.Store_5_code=c.id_store
								ORDER BY 
								    ID_Store
								 
								    ", null, [EnableFolding=true]),
								    #"Renamed Columns1" = Table.RenameColumns(Source,{{"Store_name", "Store name"}, {"Store_3_code", "Store code 3"}, {"Store_5_code", "Store code 5"}, {"Public_accessible_surface", "Public accessible surface"}, {"Storage_surface", "Storage surface"}, {"Net_internal_surface", "Net internal surface"}, {"Distribution_zone", "Distribution zone"}, {"Opening_date", "Opening date"}, {"Closing_date", "Closing date"}, {"Legal_structure", "Legal structure"}, {"Country_code", "Country code"}, {"Store_status", "Store status"}, {"Double_coque_code", "Double store code"}, {"Business_unit", "Business unit"}, {"commercial_model", "Commercial model"}})
								in
								    #"Renamed Columns1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

