table Calendar
	lineageTag: 285efc84-48a5-416e-a6eb-e4b97cf7d05e

	measure 'date max' = SELECTEDVALUE('Calendar'[Date])
		formatString: Short Date
		lineageTag: 920eef06-59f4-450e-8d0d-534d86da07b4

	column Date
		formatString: Short Date
		lineageTag: bc3caa1d-f284-436a-a4d6-5fd388ad908a
		summarizeBy: none
		isNameInferred
		sourceColumn: [Date]

		annotation SummarizationSetBy = Automatic

	column Year = year('Calendar'[Date])
		formatString: 0
		lineageTag: 0f52cdc0-db6d-437b-a243-5fb90ed7d79e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column yyyymmdd = ```
			
			FORMAT ( 'Calendar'[Date], "YYYYMMDD" )
			
			```
		dataType: int64
		formatString: 0
		lineageTag: 3a5b1045-f108-456c-b546-5fe6b73a5bf5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Calendar = calculated
		mode: import
		source = CALENDAR (DATE (2010, 1, 1), DATE (2014, 12, 31))

	annotation PBI_Id = b0912e052db140e7924a0c828c404d3d

