table 'Internet Sales'
	isHidden
	lineageTag: cff9526a-347f-435c-b0fb-3d52448a8e52

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 859b5fe3-340e-4f26-a2b9-d6ab72537c50
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3bfe6d6e-e064-4b73-bd0b-1a60f969d1fa
		summarizeBy: none
		sourceColumn: OrderDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 953779c4-ce43-4144-a4ca-b1266543b188
		summarizeBy: none
		sourceColumn: DueDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column ShipDateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: da5a941b-9003-4b58-9930-0552cc682907
		summarizeBy: none
		sourceColumn: ShipDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e3491ec1-622e-41b5-9929-b883d06d6425
		summarizeBy: count
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b6a67ee9-7296-4036-b0a0-048b8d9e1245
		summarizeBy: none
		sourceColumn: CurrencyKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column SalesTerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2724be82-7195-43c2-8433-a4dd261b867d
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Order Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: dd21aebe-a058-49ef-82ca-9382586cbcb1
		summarizeBy: none
		sourceColumn: Order Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column OrderQuantity
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: cd59a6c1-1f1b-4f1d-bc99-d3b1b9f459e1
		summarizeBy: none
		sourceColumn: OrderQuantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column TotalProductCost
		dataType: decimal
		isHidden
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 9436806f-f478-46bc-a8dd-556b3d30affe
		summarizeBy: sum
		sourceColumn: TotalProductCost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"fr-FR"}

	column SalesAmount
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 64b3866c-c1ae-477f-b11a-845764dca524
		summarizeBy: sum
		sourceColumn: SalesAmount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		isHidden
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 448de7eb-ee90-430b-8d80-8c9f6dc39fa9
		summarizeBy: sum
		sourceColumn: UnitPrice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"fr-FR"}

	partition 'Internet Sales-0216fce5-1952-4496-91fe-5c30705039fc' = m
		mode: import
		source =
				let
				    Source = Sql.Database("treez-formations.database.windows.net", "AdventureWorksDW2017", [CreateNavigationProperties=false]),
				    dbo_FactInternetSales = Source{[Schema="dbo",Item="FactInternetSales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_FactInternetSales,{"ProductKey", "OrderDateKey", "DueDateKey", "ShipDateKey", "CustomerKey", "CurrencyKey", "SalesTerritoryKey", "SalesOrderNumber", "OrderQuantity", "UnitPrice", "TotalProductCost", "SalesAmount"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"CurrencyKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"SalesOrderNumber", type text}, {"OrderQuantity", Int64.Type}, {"SalesAmount", Currency.Type}, {"TotalProductCost", Currency.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"SalesOrderNumber", "Order Number"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","SO","",Replacer.ReplaceText,{"Order Number"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"Order Number", Int64.Type}})
				in
				    #"Changed Type1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

