table Language
	lineageTag: 82438c21-b92c-4d64-a5f9-720441e35c4a

	column Language
		dataType: string
		lineageTag: 697e1f02-bbc9-4a01-9357-1c269bf76f40
		summarizeBy: none
		sourceColumn: Language

		annotation SummarizationSetBy = Automatic

	column Culture
		dataType: string
		lineageTag: 32d7ef94-bfaa-4a49-8d84-da6a88a718da
		summarizeBy: none
		sourceColumn: Culture

		annotation SummarizationSetBy = Automatic

	partition Language = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcs1Lz8kszlDSUUrN0y0tVorViVZyK0rNSwYJpRXpphUpxcYCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Language = _t, Culture = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Language", type text}, {"Culture", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

