table 'Localized Labels'
	isHidden
	lineageTag: 1943dcea-e0f0-43bc-9146-25488f416fcb

	measure 'My Report Title' = 0
		isHidden
		lineageTag: 6b0a2668-5c6e-4946-9522-3a47840d0860

	measure 'My Button Caption' = 0
		isHidden
		lineageTag: 6014704d-a490-48d1-8752-3099dd1d50ae

	measure 'My Visual Title' = 0
		isHidden
		lineageTag: 1677ccdb-501f-4661-97f4-78009792963b

	measure 'This is the sales amount by the color attribute' = 0
		isHidden
		lineageTag: 6d9dbad9-2bf0-45f6-8fd5-9560acc01393

	column unused
		isHidden
		displayFolder: unused
		lineageTag: 891ce464-77b6-495d-8cad-8d929cd299ba
		summarizeBy: none
		isNameInferred
		sourceColumn: [unused]

		annotation SummarizationSetBy = Automatic

	partition Partition = calculated
		mode: import
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

