table Products
	lineageTag: 29810423-b197-41f5-bfc6-79fe3ff1ac89

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b743fbb2-783c-4d25-a3e0-662197585ed6
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 42ef2c24-f819-4d4a-b1d9-b899c9fd8bc9
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	partition Products-e09840ab-5207-40eb-b31a-ab5a196f7b30 = m
		mode: import
		source =
				let
				    Source = Sql.Database("treez-formations.database.windows.net", "AdventureWorksDW2017", [CreateNavigationProperties=false]),
				    dbo_DimProduct = Source{[Schema="dbo",Item="DimProduct"]}[Data],
				    #"Removed Columns" = Table.SelectColumns(dbo_DimProduct,{"ProductKey", "Color"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

