table 'Translated Localized Labels'
	isHidden
	lineageTag: 31c84119-22d0-4d09-b9aa-bc78356785d5

	measure 'My Report Title Label' =
			SWITCH(USERCULTURE(),
			   "fr-FR", "Titre De Mon Rapport",
			   "it-IT", "Titolo Del Mio Rapporto",
			   "es-ES", "Título De Mi Informe",
			   "pt-PT", "Título Do Meu Relatório",
			   "My Report Title"
			)
		isHidden
		lineageTag: 032cca33-f344-4a58-a478-958525bad848

	measure 'My Button Caption Label' =
			SWITCH(USERCULTURE(),
			   "fr-FR", "Légende De Mon Bouton",
			   "it-IT", "Didascalia Pulsante Personale",
			   "es-ES", "Leyenda De Mi Botón",
			   "pt-PT", "Legenda Do Meu Botão",
			   "My Button Caption"
			)
		isHidden
		lineageTag: 8aef07f5-bc94-4b78-a05d-53022f4cb948

	measure 'My Visual Title Label' =
			SWITCH(USERCULTURE(),
			   "fr-FR", "Mon Titre Visuel",
			   "it-IT", "Il Mio Titolo Visivo",
			   "es-ES", "Mi Título Visual",
			   "pt-PT", "Meu Título Visual",
			   "My Visual Title"
			)
		isHidden
		lineageTag: 1fb1ebd1-55d8-46e3-955d-fbcfbf0f2986

	measure 'This is the sales amount by the color attribute Label' =
			SWITCH(USERCULTURE(),
			   "fr-FR", "Il S’Agit Du Montant Des Ventes Par L’Attribut Color",
			   "it-IT", "Questo È L'importo Delle Vendite In Base All'attributo Colore [Colore]",
			   "es-ES", "Este Es El Monto De Las Ventas Por El Atributo De Color",
			   "pt-PT", "Este É O Valor De Vendas Pelo Atributo De Cor",
			   "This is the sales amount by the color attribute"
			)
		isHidden
		lineageTag: 2a02a426-77f8-4591-b2ca-ecb4e2325150

	column unused
		isHidden
		displayFolder: unused
		lineageTag: 2864f406-ec2e-460c-827f-6d4a79e94f7c
		isNameInferred
		sourceColumn: [unused]

	partition Partition = calculated
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

