table 'Affected Collection'
	lineageTag: 323a027d-c39d-466f-ade9-b541b67a07c5

	column ID_Collection_aff
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d69c640c-de57-4218-ad28-3981924e2a8b
		summarizeBy: none
		sourceColumn: ID_Collection_aff

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Affected collection'
		dataType: string
		lineageTag: 74833f73-ca87-4728-bd31-7224ad0bb057
		summarizeBy: none
		sourceColumn: Affected collection

		annotation SummarizationSetBy = Automatic

	partition 'Affected Collection' = m
		mode: import
		queryGroup: '01.Dimensions'
		source = ```
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject=P_Billing_Project]){[Name=P_Project_Name]}[Data], "
				    SELECT ID_Affected_collection,
				     Affected_collection 
				    FROM `expo_self_bi_sales.affected_collection`
				    ", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Affected_collection", "Affected collection"}, {"ID_Affected_collection", "ID_Collection_aff"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

