table Calendar
	lineageTag: 4d9cc822-3533-4a62-8234-d2c655fc1487

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: eff38003-26b1-46df-a646-0e272a662a06
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_comparable_day_y1
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: b1a82226-5dfa-4d51-b3f2-7ff260063ebf
		summarizeBy: none
		sourceColumn: date_comparable_day_y1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YearWeek
		dataType: int64
		formatString: 0
		lineageTag: 454753b7-922d-4afc-986b-d9e19c85bc05
		summarizeBy: none
		sourceColumn: YearWeek

		annotation SummarizationSetBy = User

	column YearMonth
		dataType: int64
		formatString: 0
		lineageTag: 2f0c579d-a84f-40ea-94bf-02f7152c04ee
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = User

	column YearQuarter
		dataType: int64
		formatString: 0
		lineageTag: c43a7791-8082-43b3-931a-98430521e6d2
		summarizeBy: none
		sourceColumn: YearQuarter

		annotation SummarizationSetBy = User

	column YearSemester
		dataType: int64
		formatString: 0
		lineageTag: 3e765536-0a3e-4551-8b47-cae8787a65a7
		summarizeBy: none
		sourceColumn: YearSemester

		annotation SummarizationSetBy = User

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 6e17a91b-c8a3-4b57-bf75-99a11b53e4d4
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column 'YearMonth 445'
		dataType: int64
		formatString: 0
		lineageTag: 832977a4-7fed-4c00-a152-2ac071153a2e
		summarizeBy: none
		sourceColumn: YearMonth 445

		annotation SummarizationSetBy = User

	column 'YearQuarter 445'
		dataType: int64
		formatString: 0
		lineageTag: 3db758b1-064e-44d9-b84f-61df7999ea19
		summarizeBy: none
		sourceColumn: YearQuarter 445

		annotation SummarizationSetBy = User

	column 'YearSemester 445'
		dataType: int64
		formatString: 0
		lineageTag: 7f515224-92da-4573-906d-a4f39c7337c3
		summarizeBy: none
		sourceColumn: YearSemester 445

		annotation SummarizationSetBy = User

	column 'Year 445'
		dataType: int64
		formatString: 0
		lineageTag: 88fb5f8c-4133-406f-abc5-db90d6dd5aea
		summarizeBy: none
		sourceColumn: Year 445

		annotation SummarizationSetBy = User

	column YearPeriod
		dataType: int64
		formatString: 0
		lineageTag: e5d94f16-3553-44fc-a092-6cad51d622d5
		summarizeBy: none
		sourceColumn: YearPeriod

		annotation SummarizationSetBy = User

	column 'YearPeriod 445'
		dataType: int64
		formatString: 0
		lineageTag: df2e38d2-5002-4ad6-ac8b-eed50a4dec5f
		summarizeBy: none
		sourceColumn: YearPeriod 445

		annotation SummarizationSetBy = User

	partition Calendar = m
		mode: import
		queryGroup: '01.Dimensions'
		source = ```
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject=P_Billing_Project]){[Name=P_Project_Name]}[Data], "
				    SELECT
				    date_day,
				    date_comparable_day_y1,
				    id_kiabi_year_week,
				    id_year_month,
				    id_trimester,
				    id_semester,
				    id_year,
				    id_period,
				    id_kiabi_445_year_month,
				    id_kiabi_445_trimester,
				    id_kiabi_445_semester,
				    id_kiabi_445_year,
				    id_kiabi_445_period
				FROM 
				    `xfinance_solution.calendar`
				WHERE 
				    date_day >= DATE_TRUNC(
				        DATE_SUB(CURRENT_DATE(), INTERVAL 36 MONTH),
				        MONTH
				    )
				    AND date_day <= CURRENT_DATE() - 1
				    -- date_day >= (SELECT MIN(date) FROM `group-data-xretail-pro.expo_self_bi_v0.fai_ventes_departement`)
				    -- AND date_day <= (SELECT MAX(date) FROM `group-data-xretail-pro.expo_self_bi_v0.fai_ventes_departement`)
				    ", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"id_kiabi_year_week", "YearWeek"}, {"id_year_month", "YearMonth"}, {"id_trimester", "YearQuarter"}, {"id_semester", "YearSemester"}, {"id_year", "Year"}, {"date_day", "Date"}, {"id_kiabi_445_year_month", "YearMonth 445"}, {"id_kiabi_445_year", "Year 445"}, {"id_kiabi_445_semester", "YearSemester 445"}, {"id_kiabi_445_trimester", "YearQuarter 445"}, {"id_kiabi_445_period", "YearPeriod 445"}, {"id_period", "YearPeriod"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

