table Product
	lineageTag: 61c9257d-fb17-4998-8067-eb439438ae2b

	column ID_Product
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b8aada47-5024-47dc-aefe-8f1ebdc156eb
		summarizeBy: none
		sourceColumn: ID_Product

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Reference color'
		dataType: string
		lineageTag: f1281d56-81ef-47f5-acaf-6c13091f4395
		summarizeBy: none
		sourceColumn: Reference color

		annotation SummarizationSetBy = Automatic

	column Reference
		dataType: string
		lineageTag: ced91f08-9ab5-4c4f-a876-29968e3a1700
		summarizeBy: none
		sourceColumn: Reference

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: e3092b07-48dc-485a-bca5-876b5f5ecf90
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'Product collection'
		dataType: string
		lineageTag: 106d55b9-409d-400a-b75e-c37911e2c631
		summarizeBy: none
		sourceColumn: Product collection

		annotation SummarizationSetBy = Automatic

	column ID_Class
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: afe075b4-8d69-4ae5-a966-ea684d6b7051
		summarizeBy: none
		sourceColumn: ID_Class

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		queryGroup: '01.Dimensions'
		source = ```
				let
				    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject=P_Billing_Project]){[Name=P_Project_Name]}[Data], "
				    SELECT 
				    ID_Product,
				    Refco_code,
				    Reference_code,
				    Color_code,
				    Product_collection,
				    ID_Class
				    FROM `expo_self_bi_sales.product`
				    Order by ID_Product"
				    , null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Refco_code", "Reference color"}, {"Reference_code", "Reference"}, {"Color_code", "Color"}, {"Product_collection", "Product collection"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

